harshitbansal373/hacktoberfest2020

reverseString.cpp
Code to reverse a string in C++.
=> reverse a string

bubbleSort.c
=> Bubble_sort

omang_pascaltriangle.c
User is asked for the number of rows in the triangle and the triangle is printed accordingly
=> Pascal Triangle

palindrome
To find the string is palindrome or not
=> Added palindrome  program

Armstrong.py
=> Added Armstrong.py

Integer Conversion in Java
Sample code for Integer Conversion in Java
=> Integer Conversion

Parameter.java
Sample code for Parameter in Java.
=> Parameter.java

Argument.java
Sample code for Argument in Java.
=> Argument.java

Java Codes For My 5PRs
Main method executes the code.
=> Explaining Main method

firstCode
Mohamed Try to add more codes on Java so do your best to have them 5 PRs before EOD.
=> Hacktoberfest Code

Insert_at_end_linkedlist.cpp
added a c++ program to add new node with given data in a linked list at end.
=> added a c++ code for linked list.

checks_on_number.cpp
Basic code which contains menu-driven program to perform checks on a number according to choice selected by user.
=> Added a file checks_on_number.cpp

Dijkstra's_Algo.cpp
=> Shortest Path Algorithm in C++

find missing alphabet to make a string pangram
find all the missing alphabets that will make the string pangram and return the missing characters in alphabetical order.
=> Create find missing alphabet to make a string pangram

Goto Binary Search Recursion
I made this Binary Search through recursion in JAVA :))
=> Create Goto Binary Search Recursion

String with a Twist
1. The program will recieve 3 English words inputs from STDIN
These three words will be read one at a time, in three separate line
The first word should be changed like all vowels should be replaced by %
The second word should be changed like all consonants should be replaced by #
The third word should be changed like all char should be converted to upper case
Then concatenate the three words and print them
Other than these concatenated word, no other characters/string should or message should be written to STDOUT
For example if you print how are you then output should be h%wa#eYOU.
You can assume that input of each word will not exceed more than 5 chars
=> String with a Twist

open_addressing.cpp
Using C++, added the code of open addressing.
=> Added Hashing Concept

Sorting Elements in Lexicographical Order
This program sorts any ten words given by a user in a Dictionary order.
=> Create Sorting Elements in Lexicographical Order

max_subArray_sum.cpp
This is the most efficient snippet to find the maximum sub-array sum in an array.
time complexity: O(n)
=> max_subArray_sum.cpp

recussion.cpp
Coin Changing Problem Solved By Recussion in C++
=> Add Coin Change Problem Solved by Recussion 

wave sort
This sort also very important from the interview point. it asked many Mnc or tech giants like (GOOGLE, AMAZON, MICROSOFT, GOLDMAN SACHS)
=> WAVE SORT (wave array)

kadane algo
one of the most popular questions that have been asked by any interviewer finds the maximum sum of the given array in O(n). 
kadane algorithm helps you to achieve it,
=> kadane algorithm

countconcurrence.java
Count occurrence of a substring in a string using the indexOf method
=> Count occurrence of a substring

reversearra.java
Program to print the elements of an array in reverse order
=> array in reverse order

sumc++.cpp
=> Add this file

checkoddnum.py
Program to check Wheather the number is Odd or Even
=> Checkoddnum.py

CompoundInterest.java, SumOfFirstnNumbers.java
Program in Java For First N Numbers implemented.
=> Sum Of First N Numbers-JAVA

IsPrime.cs
=> added IsPrime in C#

dblLinkedList.cpp, graph/Kosaraju_algorithm, graph/bfs_dfs/bfs/BFS.py, graph/bfs_dfs/bfs/bfs.cpp, graph/bfs_dfs/dfs/DFS.cpp, graph/bfs_dfs/dfs/DFS.java, singLinkedList.cpp
Linked lists - singly and doubly in C++ added
=> added sing and double LL in CPP

sudoku_solver.py
Added a simple sudoku solver using backtracking algorithm in python programming language
=> Added a Sudoku solver using backtraking algorithm in Python

Splay_trees.c
Created a menu driven program for Splay trees search and insertion.
=> Added Splay_Trees.c

Star_Pyramid.cpp
=> Added Star_Pyramid.c #96

Matrix Multiplication
Matrix Multiplication  in java
=>  Matrix Multiplication

kadanes_algo.cpp
=> kadane_algo.cpp

PasswordGenerator.java
A simple password generator that builds passwords based on the rules of strong passwords namely at least 1 number,1 alphabet,1 special character, and length of 8 letters.
=> Password Generator code added

find_repeatng_ele_in_array.cpp
=> Created find_repeatng_ele_in_array.cpp

sort_the_zero_one_two_array.cpp
=> Created sort_the_zero_one_two_array.cpp

smartcalculator
we can get result by giving keyword as simple as 'add 2 and 3'.Here we can perform gcd,lcm,basic mathematical and trigonometrical operations.
=> smartcalculator using python and tkinter

find_reaping_missing_in_array.cpp
=> Created find_reaping_missing_in_array.cpp

reverse string variation(2).py
The reverse string is a common question but this is not a common question it has some variation in it that makes this question special.
question asked by the top MNC of the world.
-------------------------------------------------------
input="i.like.open.source.contribution.very.much"
------------------------------------------------------------
output="much.very.contribution.source.open.like.i"
#dsa
=> reverse string variation(2)

Armstrong Number.c
Added C program to check whether a given no. is Armstrong Number or not.
=> Armstrong Number.c

Sum Of Highest & Lowest Element Of An Array, Sum of elements of matrix & average.c
Data Structure In C, Program To Find Sum & Average Of Elements Of A Matrix
=> Find Sum & Average Of Elements Of A Matrix Using C

calculator using python
hello...I've created calculator using python.
=> created calculator using python

Sudoku Solver
Very optimised code for sudoku solver using backtracking in C++
=> code for sudoku solver in C++

Basics of Two pointers
=> Create Basics of Two pointers

Gold Mine problem
C++ program to solve Gold Mine problem
=> Gold Mine problem

Depth First Search(DFS)
Implementation of Depth First Search(DFS)
=> Depth First Search(DFS)

.idea/.gitignore, .idea/Hactoberfest2020.iml, .idea/inspectionProfiles/profiles_settings.xml, .idea/misc.xml, .idea/modules.xml, .idea/vcs.xml, greatest of three numbers.py
Program to find the largest among three numbers in python.
=> Added greatest of three numbers

gcd_lcm c
this program is used to calculate gcd and lcm in c
=> Create gcd_lcm c

Sum of Natural numbers using recursion in C
HOPE THIS WILL CONTRIBUTE IN OPEN SOURCE
=> Create Sum of Natural numbers using recursion in C

Dutch_National_Flag_Problem.cpp
Sort an array of 0's,1's and 2's(Sort Colors)
=> Add Dutch National Flag Problem

Bowling Strategy.cpp
CodeChef Problem Code: BOWLERS
=> Bowling Strategy.cpp

circular_queue.cpp
=>  circular_queue.cpp

Algorithm_C/all_pair_shortest_path.c, Algorithm_C/fractional_knapsack.c, Algorithm_C/kruskal.c, Algorithm_C/longest_common_subsequence.c, Algorithm_C/n_queens.c, Algorithm_C/naive_string_matching_algorithm.c, Algorithm_C/rabin_karp.c
Algorithms List
- All Pairs Shortest Path 
- Fractional Knapsack 
- Kruskal's Minimum Spanning Tree 
- Longest Common Subsequence
- Naive String Matching
- Rabin Karp 
- N Queens
=> Algorithm Implementation in C

Beans Canvas/Js/script.js, Beans Canvas/index.html, Beans Canvas/style.css
An interactive canvas background using HTML,CSS and Javascript.
=> Beans Canvas

areaCircumference.c, greatest of three numbers.py
I tried to modify some of the codes, in order to make it more sophisticated
=> some modifications

Stack_Queue/README.md, Stack_Queue/queue.py, Stack_Queue/stack.py
Python scripts to understand the concept of Stack & Queue seperately plks review my PR. Contributed for Hacktoberfest-2020
Solved issue #265 .Always open for ur valuable suggestions.Thank You!!
=> Stack & Queue implementaion in python

optimize bubble sort.cpp
this is one level up bubble sort. which helps you to sort very fast and executed in minimum time.
this question asked by FAANG.
this will also help you to find out no. swaps to be taken by array so it can right form or in sorted order.
=> optimize bubble sort

Backtracking/Sudoko Solver using Backtracking.ipynb, Backtracking/Sum of Subset problem using Backtracking.ipynb
kindly review the code and merge the PR.
=> Added some Backtracking algos

bubble_sort.c
An issue was raised, for uploading sorting algorithms. Here is Bubble Sort in C.
=> Bubble Sort in C

DESKTOP APPLICATION IN PYTHON.py
create a desktop application with the help of python and Tkinter module. it helps the kid to learn the basics of python. which is far better than pdf learning.it have all content for kids to learn the basics of python
#python development
=> Desktop application in python

counting elements in O(n)
this is a basic level question asked by TCS, Wipro, Accenture, and many more.
counting element.
=> counting elements in O(n) time

rotate array 90deg anticlockwise
this is also a variation of rotation topic in the array. the only thing is you have to rotate the given array 90-degree anticlockwise but in-place that is the twist and make this question good.
this question is asked by many MNC.
=> Rotate array 90 deg anticlockwise(in-place)

rotate array 90 degree cloclwise
this is an amazing question from an array that has been asked by many tech giants companies like(AMAZON, GOOGLE, GOLDMAN SACHS, MICROSOFT) many more.
you have to rotate the array by 90-degree clockwise but the twist does it(IN-Place). that makes this question very good and asked by many interviewers.
happy coding!
=> Rotate by 90 degree clockwise

double-headed-arrow-pattern.py
A Double Headed Arrow Pattern using Python3 with a initial input of 7 number of rows.
=> Double-headed-arrow-pattern.py

heapSort.cpp, reverse_a_queue.cpp, reverse_a_stack_rec.cpp, sum_of_nodes_BT.cpp
Kindly review and accept my work
=> adding dsa problems in c++

FactLargeNo.c
You Can Find Factorial Of any of the Number( upto 100000).
=> Factorial Of Large Number

Sum of first and last digit of a number.c
Program for finding sum of first and last digit of a number in C
=> Sum of first and last digit of a number

fibonacci.c
given a number n, nth fibonacci number is printed
=> code to find nth fibonacci number

Algorithm_C/quick_sort.c
I am new to open source. Please merge and label it as hacktoberfest-accepted.
=> Added quick sort program in Algorithms

graph/UnionFind_algorithm/UnionFind.py
**Union Find** (also known as _Disjoint Set Union_) is a very popular algorithm for finding connected components and similar tasks in graph theory. Implemented in Python.
=> Python implementation of Union Find algorithm

selectionsort.c
=> Implemented selection sort program in c

stringsort.c
given n strings, the sorted strings are printed
=> code to sort strings

zigzag.c
given a size n, a matrix with size n*n and its numbers in zigzag pattern is printed
=> code to print a zigzag matrix

kmp.c
a very detailed code explaining the kmp algorithm
=> detailed code for kmp algorithm

Goto Binary Search
This is the simple Binary Search program I made through JAVA
=> Create Goto Binary Search

cpp/Kruskal_MST.cpp
**Kruskal's Algorithm** is a popular algorithm for finding the _Minimum Spanning Tree(MST)_ of a weighted un-directed graph.
=> Implementation of Kruskal's algorithm using Union Find in C++14

threaded_binary_tree.cpp
=> added threaded binary tree

NoOfCombinationFinder.c
It Takes  number of items and the number of selections and give the number of possible combination as per your no of selections and no of choices :)
=> No Of Combinations Program in C

cpp/spiral array.cpp
=> Added Spiral array program in cpp

ArmstrongNumber(cpp).cpp
A c++ program to find Armstrong number
=> Added ArmstrongNumber in cpp

Function_definition_and_call.py
Based on function definition and call 
Write functions for addition, subtraction, multiplication and division of all numbers from a list and print the final results of each function. In your main program, ask for number of elements, and actual elements of the list. Pass the list to each function call of arithmetic operations.
=> Created Function_definition_and_call.py

STL sort for array
This function helps you a lot in competitive or basic programming contests.
when you have to sort an array in a minimum interval of time. because in a programming contest you have minimum time to solve the question so this will helps you to achieve it
syntax is:
sort(arrar_name, array_name+array_size);
=> create STL sort() for an array in c++

largest_number_array.py
added largest number in array program in python
=> largest_number_array.py

file_sum_count
This is a Python program which displays the sum of all numbers present in a file which is entered as an input.
This program uses the concept of Regular Expressions in Python.
Some sample file links are:
https://www.py4e.com/code3/mbox-short.txt
https://www.py4e.com/code3/mbox.txt
http://py4e-data.dr-chuck.net/regex_sum_975455.txt
http://py4e-data.dr-chuck.net/regex_sum_42.txt
=> File_sum_count

bellman.py, dijkstra single source algo.py
=> bellman ford algo

morris_preorder_traversal.cpp
Add Morris preorder traversal for traversiing a tree in O(1) space.
Please review and merge the changes.
=> Add Morris traversal for preorder

PortScanning_EthicalHacking/advancescanner.py, PortScanning_EthicalHacking/portscan1.py, PortScanning_EthicalHacking/portscan2.py, PortScanning_EthicalHacking/readme.md, PortScanning_EthicalHacking/retbanner.py
PortScanning_EthicalHacking
This folder contains port scanners that help you and your organization to check if there are any unnecessary ports that are open which leads to data loss and getting hacked or attacked by malicious files.
=> PortScanning_EthicalHacking for knowing your weaknesses and staying safe

power.cpp
Link: https://leetcode.com/problems/powx-n/
Implement pow(x, n), which calculates x raised to the power n.
=> Leetcode: Problem #50

sqrt.cpp
Link:https://leetcode.com/problems/sqrtx/
Implement int sqrt(int x).
Compute and return the square root of x, where x is guaranteed to be a non-negative integer.
Since the return type is an integer, the decimal digits are truncated and only the integer part of the result is returned.
=> Leetcode: Problem #69

cpp/Palindrome.cpp
=> Palindrome.cpp

Python/star.py
Printing star pattern in range given input by the user and if true it prints pattern if false reverses the pattern.
=> Added Star.py

HTML_hover_blocks/index.html, HTML_hover_blocks/main.js, HTML_hover_blocks/style.css
=> HTML small project hover blocker

C/queue_array.c
Implementation of Queue Data Structure using Array
=> Queue using Array

Algorithms/SelectionSort/selectionsort.go
Added selection sort code for GO lang  #46
=> Added selectionsort.go

C/product simples.c
This code, find the product of something
=> Create product simples.c

Python/finding the percentage.py
I had solve the hacker rank  problem of finding the percentage in python.
Please check.
=> Created the finding percentage.py

Python/object_size.py
Determine the size of an object using Python
=> Added object_size.py

Projects/Python/altering files and folders
=> Create altering files and folders

Algorithms/BinarySearch/binarysearch.c
Binary Search on a array in C programming language.
=> Binary Search

Python/maze_A*
A* algorithm to solve maze problem in python
=> A* alogorithm

cpp/SLL.cpp
Added Singly Linked List in C++ language with more functionalities than previously added. Please check earlier codes for functionalities while checking my code.
=> Added SLL.cpp

C/sparse.c
For Hacktoberfest 2020
Please merge as ASAP
=> Sparse Matrix

cpp/matrix_sub.cpp, cpp/merge_sort.cpp
created a program on subtraction of two matrixes in c++.
=> matrix_sub.cpp

C/bintodec.c, C/dectobin.c, C/hexadectodec.c, cpp/binarytodecimal.cpp, cpp/primeorcomposite.cpp
created a program to convert decimal number to binary in c.
=> dectobin.c

Python/removeNthNodeFromEnd.py
Given the `head `of a linked list, remove the `nth `node from the end of the list and return its head.
```
Input: head = [1,2,3,4,5], n = 2
Output: [1,2,3,5]
```
Constraints:
- The number of nodes in the list is `sz`.
- `1 <= sz <= 30`
- `0 <= Node.val <= 100`
- `1 <= n <= sz`
=> Add famous question of FAANG companies [removeNthNodeFromEnd.py]

Python/floydtriangle
write code to display a diamond pattern
=> diamondpattern

C/Acromatic_String.c
Acromatic String Program added
=> Acromatic String Program added

C/Mean_Standard_deviation.c
Mean and Standard Deviation Program added
=> Mean and Standard Deviation Program added

C/Employee_Details_Using_Structure.c, C/nCr_factor.c
Find nCr Factor Using C Program added.
=> Find nCr Factor Using C Program added.

Algorithms/Bellman/BellmanFord.java, Algorithms/BinarySearch/BinarySearch.java, Algorithms/CountSort/CountingSort.java, Algorithms/HeapSort/HeapSort.java, Algorithms/Kruskal/Kruskal.java, Algorithms/MinHeap/MinHeap.java, Algorithms/QuickSort/QuickSort.java
Bellman Ford Algo, Quick Sort, Count Sort, MinHeap etc
=> Added missing code snippets in Java

cpp/double link list.cpp
A doubly linked list program in c++ language.
=> Added a doubly linked list program

cpp/Inorder traversal_without_recursion.cpp
Inorder traversal without recursion.
=> Inorder_traverssal_with_stack

Algorithms/Dijkstra/Dijkstra_algorithm.py, Algorithms/Knapsack/Fractional_knapack_greedy.py
Contribution towards hacktober fest 2020.
=> Fractional knapsack

Algorithms/BubbleSort/bubblesort.go
added code for bubble sort in Go lang #46 #23
=> Added bubblesort.go

Projects/Python/Car_Plates_Detection.py
Please have a look at my file and accept my pull request.
=> Car Number Plate Detection

Projects/Lightbox/app.js, Projects/Lightbox/index.html, Projects/Lightbox/style.css
=> Added my LightBox project

Algorithms/Set Covering Problems/8 Greedy set covering.py, Algorithms/Set Covering Problems/Input Greedy set covering.py
create an algoritma to solve the set covering problem with greedy method , build in python languange
=> Set Covering problem with greedy method

C/pentagon pattern.c
H! there its YoGesH JAdhaV studing in 3rd year engineering and would like to contribute from my side,ThaNk YoU
=> Pentagon pattern in C

Projects/Python/Hours_vs_Scores_Prediction(96% accuracy)
Implementation of LassoLars linear model on hours vs student scores prediction with an increased accuracy of 96%.
=> Hours_vs_Scores_Prediction(96% accuracy)

Java/SlidingWindow.java
Using Arrays, deque and linkedlist
=> Added SlidingWindow in java

Python/any base till hexa conersion to decimal.py, Python/compliment of base till hexa.py
1st code is for conversion from any base till hexa to decimal 
2nd code is for complement of a Number  in any base till hexa
=> 2 python codes for complement and base conversion 

Python/BinaryTree.py
Adding a Binary Tree program with multiple related methods.
=> Added BinaryTree.py

cpp/template class.cpp
A template class concept in c++.
=> Added a template class program

Python/CountingSort.py
Adding Counting sort algorithm
=> Counting sort

Projects/Python/Board.py
=> Tetris Game using Python

Java/sequenceChecking.java
This method can be used to check a string's sequential order. We can make this String not contains character ( A B C) or numbers (1 2 3 ) in a sequential order.
=> Create a method for sequence checking

Python/calender.py, Python/sqrt-number.py
I added a condition that only calculates square root if it is positive.
=> added condition that number must be positive for square root calculation

C/guessTheNumber.c
This is a number guessing game between 1 to 100. Through srand() and rand() we'll generate a random number between 1 to 100 and then we will make guesses if we enter lesser than random number it will prompt to enter greater number and vice versa.
And then it will tell us in how many steps we achieved that.
=> guessTheNumber

cpp/move_negative_elements_one_side_array.cpp
c++ program to move negative elements in an array to one side without sorting.
order does not matter here.
Used two approches for the problem.
=> Added C++ program to move negative elements in an array to one side.

Java/KlargestElement.java
The algorithm is implemented in Java with test driver.
=> Algorithm to find the k-largest element in an array

Python/binary_search.py
iterative way of binary search in python.
=> Iterative binary_search.py

cpp/MinEditDistance.cpp
C++ program to solve minimum edit distance problem-
To convert string s2 to s1 using minimum number of operations(edit,add or delete),
Using Dynamic Programming approach
=> Added Minimum Edit Distance solution using DP

C/Tower Of Hanoi.c
Contains the code for Tower Of Hanoi Problem.
=> Tower Of Hanoi

URL-Shortener/LICENSE, URL-Shortener/README.md, URL-Shortener/package-lock.json, URL-Shortener/package.json, URL-Shortener/server.js, URL-Shortener/shortner.js, URL-Shortener/static/index.html, URL-Shortener/static/jquery.min.js, URL-Shortener/static/script.js, URL-Shortener/static/style.css
=> Added file

Java/DoublyLinkedListAlgoritm.java
I added a Doubly Linked List in Java.
=> Adding a Doubly Linked List

Python/searchNsort.py, cpp/CRC.cpp, cpp/polynomialAddition.cpp
I've added CRC or Cyclic Redundancy Check, a method of detecting accidental changes/errors in the communication channel, and
polynomial addition code in C++ and also binary and linear searches and bubble, selection, and insertion sort code as a menu-driven program in python.
=> Added CRC, polynomial addition and search and sort algorithms

Java/ThreadPoolPerformance.java
This is the thread pool project I am studying recently
=> ThreadPoolPerformance

Python/primenumber.py
Added a missing condition that if we give 1 as input then what will happen.
=> Added a missing condition

C/array.c, C/average.c
please label hacktoberfest-accepted, thx.
=> add average and array in C

binarySearch.cpp
=> A new file of Binary Search is Added

cpp/JosephusProblem.cpp
=> Add JosephusProblem.cpp

cpp/Prime_number_check.cpp
=> Midhat-fatima-pucit

cpp/Atcoder Educational DP/chessmetric.cpp, cpp/Atcoder Educational DP/coin.cpp, cpp/Atcoder Educational DP/deque.cpp, cpp/Atcoder Educational DP/frog.cpp, cpp/Atcoder Educational DP/frog2.cpp, cpp/Atcoder Educational DP/grid.cpp, cpp/Atcoder Educational DP/kanpsack2.cpp, cpp/Atcoder Educational DP/knapsack.cpp, cpp/Atcoder Educational DP/lcs.cpp, cpp/Atcoder Educational DP/longestPath.cpp, cpp/Atcoder Educational DP/stones.cpp, cpp/Atcoder Educational DP/sushi.cpp, cpp/Atcoder Educational DP/vacation.cpp
Some solutions of Atcoder Educational DP contest in cpp.
=> added solutions of Atcoder EducationalDP contest

cpp/Queue from Stacks.cpp
This code demonstrates the working of a Queue using two stacks.
=> Added Queue from stacks problem

C#/EventCenter.cs
=> Add EventCenter.cs

Python/shell_sort.py
Implement shell sort algorithm in Python, includes big O time and space complexity
=> Add Python/shell_sort.py

Java/Fibonacci using DP, Java/Searching in sorted 2D Array, Java/Spiral Display 2D Array
Program to get the nth Fibonacci number in Java (Starting from 0)
=> Create Fibonacci using DP

cpp/Delete_middle_element_of_stack_recursion.cpp
Code to delete middle element of stack using recursion
=> Add Delete_middle_element_of_stack_recursion.cpp

Python/greatest of three numbers.py
Hey, I just try to add some more value to the program by handling the ValueError as if someone give a value that is not integer or float than that Error in red colour don't seem good. So, handling it is a good practice. 
Please review it and if it's ok than merge it.
=> Update greatest of three numbers.py

Java/BinarySearch.java
Given a sorted array, it returns the index of a given number in linear time, if the number is not in the array it returns -1
=> added binary search algorithm in java

Java/rockPaperS.java
Added rock paper scissors program in java
=> rock paper scissors

Projects/Python/Image-to-ascii/Image-to-ascii.py
Writtem a white back while learning PIL, Fully documented :)
=> Added a Python Project (Image To ASCII Image)

Python/Depth_First_Search.py, cpp/Dijkstra.cpp
A simple example of the AI Search algorithm - Depth First Search
=> Depth First Search Algorithm

cpp/LowestCommonAncestor.cpp
happy hacktoberfest 2020 🥳 🥳 🥳 🎉 🎉 🎉
=> Lowest Common Ancestor

Python/bw_image_scraper.py
Mainly for OpenCV parsing 
Hacktoberfest entry (:
=> Simple Program Made for Scraping Images and Converting to B&W

Python/Lcis.py
LCIS- Largest Common Increasing Subsequence
The program is basically used to find the Length of Largest Common Increasing Subsequence.
Approach used - Dynamic Programming
=> ADDED "Largest Common Increasing Subsequence" .

JavaScript/CompareJsonSchema.js
check weather schema is equal or not
=> comapre two json schema

C/Amazing_prog.c
=> Amazing_prog.c

Python/simplepythonportscanner.py
=> Simple Python Port Scanner

cpp/KMP_Algorithm.cpp
Kindly accept this commit for hacktoberfest 2020, and add a label "hacktoberfest-accepted"
=> added kmp algorithm in cpp

Python/dice.py
=> add dice program

C/Queue_using_LinkedList
The C program presents all the basic operations on a Queue.
The Queue is constructed/represented with the help of a Linked List.
The basic operations on a Queue that are included in the program are:
1.Insert
2.Delete
3.Display the element at the front
4.Display all elements of the queue
Hope you like it...
=> Queue_using_LinkedList

Twitter-Bot/README.md, Twitter-Bot/follow_your_followers.py
A twitter bot that can follow back your followers and you don't have to go to their profiles individually to follow them.
=> Follow back your all followers or selected ones

JavaScript/ReactionTimer.html
Click the shapes as soon as possible
=> addingReactionTimer

Java/MainClass.java, Java/TowerOfHanoi.java
This code provides the solution of "Tower of Hanoi" problem with 3 disks.
=> Adding TowerOfHanoi.java

Python/Fake_news detection.py
=> Create Fake_news detection.py

C/e^x_series.c
Added a program to find the value of e^x using e^x series expansion.
=> Added a C program of e^x ( Hacktoberfest 2020)

C/oddeven.c, Python/sudoku.py
=> odd or even

C/Factorial.c
This program, calculates the factorial of a given number through the concept of RECURSION.
=> Factorial through Recursion

Python/ginorts.py
ginortS
Problem Statement
You are given a string S, which contains alphanumeric characters only.
Your task is to sort the string in the following manner:
All sorted lowercase letters are ahead of uppercase letters.
All sorted uppercase letters are ahead of digits.
All sorted odd digits are ahead of sorted even digits.
Sample Input
Sorting1234
Sample Output
ginortS1324
=> added ginortS.py a Hackerrank question

JavaScript/IsOddIsEven.js
Javascript module to check is variable is a Number, and is it Odd, or is it Even.
=> Added isNumber isOdd isEven functions

Python/interpolation_search.py
=> search interpolation
